name: Tests

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    strategy:
      matrix:
        node: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Lint code
        if: ${{ matrix.node == '16.x' }}
        run: npm run lint

      - name: Run tests
        run: npm run test
